### ISSUE TITLE
"View" buttons on the list of opps belonging to an organization should link to that specific opp.

### ISSUE THREAD

**Issue by razzlepdx** [hendricksonsarahl/voluntr#118]

**Comment by rylandbell** [comment]
I just looked at the mock-up for the org's View Opp page for the first time in a while. When I wrote it, I just copy-pasted the HTML from the volunteer view-opp page, and removed the buttons. The volunteer version of this view has changed a bit since then (and has been converted into a Jinja template), so I'd recommend starting with a fresh copy-paste of this code, rather than the code currently in the mock-up. @razzlepdx

**Comment by razzlepdx** [comment]
Thanks, @rylandbell!  I will do that.
