### ISSUE TITLE
Create data set to be used in testing and views

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#16]
We will need to brainstorm some data types, come up with some sample data sets, and have a place for some basic starter data to be stored that we can pull from when testing and populating Nonprofit Orgs and Opportunities in the views. 
Some examples to start off - 
<b>Organization Data:</b>
<ul>
<li>Nonprofit name</li>
<li>Nonprofit contact name</li>
<li>Nonprofit contact email</li>
<li>Nonprofit address</li>
<li>unique ID</li>
</ul>
<b>Opportunity Post Data:</b>
<ul>
<li>Nonprofit ID</li>
<li>Nonprofit name</li>
<li>Opportunity address/location</li>
<li>Opportunity title</li>
<li>Opportunity description</li>
</ul>

**Comment by AdamD-2096** [comment]
we'll also need to think up if any of those fields should be their own objects.
i think this could be a great topic for our next meet.
we could all start from this and work up then come together and talk

**Comment by razzlepdx** [comment]
Other ideas for Opportunity Posts:

- Time Commitment
- Opportunity Type/Category (animals, environment, etc)
- Description of next steps

**Comment by AdamD-2096** [comment]
unless you want something basic set up for now??
we can always add to it and change it.
although it would probably remain detached.. until we get everything else in place for it.

**Comment by hendricksonsarahl** [comment]
I'm open to all of these ideas and more! I think having someone take the lead on getting this brainstorming started would be a great start, and like @AdamD-2096 said, we can always change and add to it as we go

**Comment by AdamD-2096** [comment]
would you like me to get some models started. in code with the basic stuff we know we'll need?
i'd keep it just as a separate file we could connect to later since we can't connect it just yet.
but then at least we'd have a starting point

**Comment by hendricksonsarahl** [comment]
Sounds like a great start, go for it! Feel free to assign yourself to this issue for now

**Comment by rylandbell** [comment]
Sounds good @AdamD-2096 . I think it will help to have a starting point written down, which will surely help raise some good questions to discuss.

**Comment by razzlepdx** [comment]
I think this issue needs to stay open until we have sample data collected and formatted in a way that we can add it to the database :)

**Comment by AdamD-2096** [comment]
i figured that was a separate issue.
i thought everything mentioned in this issue was taken care of? 
am i missing something?
sorry i'm confused now...

just going to go over what i thought to see where i'm off

this issue was basically about how to set up the models so that we can start testing things
and then we need to get a file with "data" to read into the db models
and then we'll need the code to parse through that file to feed it into said db
then we can finally use said data to test everything else we've built.

this is a lot of stuff and i figured that the file and the code to read the file would be two separate issues that i agree are related to this one and they are dependent on each other. but are they the same issue?

**Comment by razzlepdx** [comment]
resolved in PR #62
